Support HTTP basic authentication
kakao/kafka-connect-web pull request #5
Opened 2023-08-14 10:42 UTC by Dawnpool

Kafka Connect REST API also supports HTTP basic authentication, as detailed in the ([Connect REST API documentation](https://docs.confluent.io/platform/current/security/basic-auth.html#kconnect-rest-api)). However, the current state of this project does not support it yet. I am writing this PR to make compatibility with the basic auth feature.

The changes are
- Enabling compatibility with basic auth API server by configuring username and password through environment variables
- Adding brief instructions for the basic auth option in README.md
- Updating eslint and eslint-plugin-vue versions to prevent errors after 'npm run build' command

I kindly request a comprehensive review and expect your valuable feedback. Thank you.

2023-08-14 10:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kakao/kafka-connect-web?pullRequest=5) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kakao/kafka-connect-web?pullRequest=5) before we can accept your contribution.<br/><hr/>**dawn.choi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kakao/kafka-connect-web?pullRequest=5) it.</sub>

2023-08-21 01:01 UTC, AndersonChoi requested changes

2023-08-21 01:01 UTC, AndersonChoi commented on README.md
> +npm run serve
Put it in a code block like this:
```
$ export VUE_APP_AUTH_USERNAME={username}
$ export VUE_APP_AUTH_PASSWORD={password}
$ npm run serve
```

2023-08-21 01:01 UTC, AndersonChoi commented on README.md
> +Kafka Connect REST API supports HTTP basic authentcation. ([Connect REST API](https://docs.confluent.io/platform/current/security/basic-auth.html#kconnect-rest-api))
Please correct the typo `authentcation`

2023-08-21 01:01 UTC, AndersonChoi commented on README.md
> +To prevent CORS errors, you should configure the CORS settings in the reverse proxy instead of the connect-distributed.properties file.
The information on how to set up a reverse proxy is incomplete, so please write how to set it in more detail.

2023-08-23 09:39 UTC, Dawnpool commented
@AndersonChoi 
I have applied all your feedback, but I'm still not sure if the information on reverse proxy setup is good enough.
Please check and let me know if anything is insufficient. Thank you so much!

2023-09-02 06:53 UTC, Dawnpool commented
@AndersonChoi 
Hi, I just added more explanations about why reverse proxy is necessary and a note when using multiple kafka connect servers. Please check and let me know if anything looks awkward or not enough. Thank you!

2023-09-05 04:48 UTC, AndersonChoi approved these changes

2023-09-05 04:48 UTC, merged